require("lib/complex")

describe("Complex number operations", function()
    it("should add complex numbers correctly", function()
        local c1 = complex.new(1, 2)
        local c2 = complex.new(3, 4)
        local c3 = complex.add(c1, c2)
        assert.are.equal(4, c3.r)
        assert.are.equal(6, c3.i)
    end)

    it("should subtract complex numbers correctly", function()
        local c1 = complex.new(1, 2)
        local c2 = complex.new(3, 4)
        local c3 = complex.sub(c1, c2)
        assert.are.equal(-2, c3.r)
        assert.are.equal(-2, c3.i)
    end)

    it("should multiply complex numbers correctly", function()
        local c1 = complex.new(1, 2)
        local c2 = complex.new(3, 4)
        local c3 = complex.mul(c1, c2)
        assert.are.equal(-5, c3.r)
        assert.are.equal(10, c3.i)
    end)

    it("should invert complex numbers correctly", function()
        local c = complex.new(1, 2)
        local c2 = complex.inv(c)
        assert.are.equal(0.2, c2.r)
        assert.are.equal(-0.4, c2.i)
    end)

    it("should raise complex numbers to power correctly (case 1)", function()
        local c = complex.new(1, 2)
        local c2 = complex.pow(c, 2)
        assert.are.equal(-3, c2.r)
        assert.are.equal(4, c2.i)
    end)

    it("should raise complex numbers to power correctly (case 2)", function()
        local c3 = complex.new(5, 8)
        local c4 = complex.pow(c3, 3)
        assert.are.equal(-835, c4.r)
        assert.are.equal(88, c4.i)
    end)

    it("should calculate magnitude correctly", function()
        local c = complex.new(3, 4)
        local m = complex.mag(c)
        assert.are.equal(5, m)
    end)
end)